version: 0.2

phases:
  install:
    commands:
      # Authenticate Docker to AWS ECR
      - echo "Authenticating to AWS ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 287870619061.dkr.ecr.us-east-1.amazonaws.com
      - echo "ECR authentication completed."

  deploy:
    commands:
      # Pull the Docker image from ECR
      - echo "Pulling Docker image from ECR..."
      - docker pull 287870619061.dkr.ecr.us-east-1.amazonaws.com/docker-website-repo:latest

      # Run the container, exposing the React app on port 3000 inside the container, and mapping it to port 80 on the host
      - echo "Running Docker container..."
      - docker run -d -p 80:3000 287870619061.dkr.ecr.us-east-1.amazonaws.com/docker-website-repo:latest

artifacts:
  files:
    - '**/*'
